name: Build, test, and doc update
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  run:
    if: ${{ github.ref == 'refs/heads/master' || (github.event_name == 'pull_request' && startsWith (github.head_ref, 'doc')) }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: avsm/setup-ocaml@v1
      with:
        ocaml-version: '4.10.0'
    - run: opam pin . --with-doc -y
    - run: opam exec -- dune build @doc
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/default/_doc/_html/
